trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: generate_version
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: test
          arguments: -v minimal
          projects: tests/Facet.Tests.Unit
      - task: GithubFlowVersion@0
        inputs:
          gitHubConnection: 'Jarlotee'
      - script: echo "$(GithubFlow.Tag) $(GithubFlow.Body)"
      - script: ls -a
      - task: GithubFlowRelease@0
        inputs:
          githubConnection: 'Jarlotee'
          tag: '$(GithubFlow.Tag)'
          body: '$(GithubFlow.Body)'
          draft: true