trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: build
    jobs:
      - job: build
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: test
              arguments: -v minimal
              projects: tests/Facet.Tests.Unit
          - task: GithubFlowVersion@0
            inputs:
              gitHubConnection: 'Jarlotee'
          - script: echo "$(GithubFlow.Tag) $(GithubFlow.Body)"
          - script: ls -a
          - script: echo "Deploying Container"
  - stage: deploy_dev
    jobs:
      - deployment: deploy_dev
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
              - script: echo "deploying $(stageDependencies.build.build.outputs['GithubFlow.Tag']) to dev"
  - stage: deploy_qa
    jobs:
      - deployment: deploy_qa
        environment: qa
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "deploying Qa"
  - stage: deploy_prod
    condition: false
    jobs:
      - deployment: deploy_prod
        environment: prod
        strategy:
          runOnce:
            deploy:
              steps:
              - script: echo "deploying Prod"
      - job:
        steps:
          - task: GithubFlowRelease@0
            inputs:
              githubConnection: 'Jarlotee'
              tag: '$(GithubFlow.Tag)'
              body: '$(GithubFlow.Body)'
              draft: true
      