trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: build
    jobs:
      - job: build_job
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: test
              arguments: -v minimal
              projects: tests/Facet.Tests.Unit
          - task: GithubFlowVersion@0
            name: version
            inputs:
              gitHubConnection: 'Jarlotee'
          - script: echo "deploying container"
          - task: GithubFlowRelease@0
            inputs:
              githubConnection: 'Jarlotee'
              tag: '$(version.tag)'
              body: '$(version.body)'
              draft: true
  - stage: dev_deploy
    dependsOn: 
    - build
    jobs:
      - deployment: dev_deployment
        environment: dev
        variables:
          tag: $[stageDependencies.build.build_job.outputs['version.tag']]
        strategy:
          runOnce:
            deploy:
              steps:
              - script: echo "deploying [$(tag)] to dev"
  - stage: qa_deploy
    dependsOn:
    - build
    - dev_deploy
    jobs:
      - deployment: qa_deployment
        environment: qa
        variables:
          tag: $[stageDependencies.build.build_job.outputs['version.tag']]
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "deploying [$(tag)] to qa"
  - stage: prod_deploy
    dependsOn:
    - build
    - qa_deploy
    jobs:
      - deployment: prod_deployment
        environment: prod
        variables:
          tag: $[stageDependencies.build.build_job.outputs['version.tag']]
        strategy:
          runOnce:
            deploy:
              steps:
              - script: echo "deploying [$(tag)] to prod"
      - job: github_release
        variables:
          tag: $[stageDependencies.build.build_job.outputs['version.tag']]
          body: $[stageDependencies.build.build_job.outputs['version.body']]
        steps:
          - task: GithubFlowRelease@0
            inputs:
              githubConnection: 'Jarlotee'
              tag: '$(tag)'
              body: '$(body)'
      