trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: build
    jobs:
      - job: build
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: test
              arguments: -v minimal
              projects: tests/Facet.Tests.Unit
          - task: GithubFlowVersion@0
            name: version
            inputs:
              gitHubConnection: 'Jarlotee'
          - script: echo "deploying container"
          - task: GithubFlowRelease@0
            inputs:
              githubConnection: 'Jarlotee'
              tag: '$(tag)'
              body: '$(body)'
              draft: true
  - stage: deploy_dev
    jobs:
      - deployment: deploy_dev
        environment: dev
        variables:
          tag: $[stageDependencies.build.build.outputs['version.tag']]
        strategy:
          runOnce:
            deploy:
              steps:
              - script: echo "deploying [$(tag)] to dev"
  - stage: deploy_qa
    jobs:
      - deployment: deploy_qa
        environment: qa
        variables:
          tag: $[stageDependencies.build.build.outputs['version.tag']]
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "deploying [$(tag)] to qa"
  - stage: deploy_prod
    jobs:
      - deployment: deploy_prod
        environment: prod
        variables:
          tag: $[stageDependencies.build.build.outputs['version.tag']]
        strategy:
          runOnce:
            deploy:
              steps:
              - script: echo "deploying [$(tag)] to prod"
      - job:
        variables:
          tag: $[stageDependencies.build.build.outputs['version.tag']]
          body: $[stageDependencies.build.build.outputs['version.tag']]
        steps:
          - task: GithubFlowRelease@0
            inputs:
              githubConnection: 'Jarlotee'
              tag: '$(tag)'
              body: '$(body)'
      