trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: generate_version
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: test
          arguments: -v minimal
          projects: tests/Facet.Tests.Unit
      - task: GithubVersion@0
        inputs:
          gitHubConnection: 'Jarlotee'
      - script: echo "$(github-version--name) $(github-version--prerelease) $(github-version--body)"
      - script: ls -a
      - task: GithubRelease@0
        inputs:
          githubConnection: 'Jarlotee'
          tag: '$(github-version--name)'
          body: '$(github-version--body)'
      
