trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: generate_version
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: test
          arguments: -v minimal
          projects: tests/Facet.Tests.Unit
      - task: GithubVersionTask@0
        inputs:
          GitHubConnection: 'Jarlotee'
      - script: echo "$(github-version--name) $(github-version--prerelease) $(github-version--body)"
      - script: ls -a
      - task: GitHubRelease@1
        inputs:
          gitHubConnection: 'Github'
          repositoryName: '$(Build.Repository.Name)'
          action: 'create'
          target: '$(Build.SourceVersion)'
          tagSource: 'userSpecifiedTag'
          tag: '$(github-version--name)'
          releaseNotesSource: 'inline'
          releaseNotesInline: '$(github-version--body)'
          isPreRelease: true
          changeLogCompareToRelease: 'lastFullRelease'
          changeLogType: 'issueBased'
