trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: generate_version
    steps:
      - script: git describe --abbrev=0 --tags --match "[0-9]*.[0-9]*.[0-9]*" --exclude "[0-9]*-*"
      - task: GithubVersionTask@0
        inputs:
          GitHubConnection: 'Jarlotee'
  - job: dotnet_test
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: test
          arguments: -v minimal
          projects: tests/Facet.Tests.Unit
